# Generated by Django 6.0.6 on 2026-10-06 03:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_address'),
        ('products', '0003_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Customers can type it in any case.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]+$', 'Use letters, numbers, and dashes only.')])),
                ('percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Percent off')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave empty to never expire.', null=True, verbose_name='Expires at')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to retire the code.', verbose_name='Active')),
                ('products', models.ManyToManyField(blank=True, help_text='Leave empty to discount the whole order.', related_name='discount_codes', to='products.product')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.discountcode'),
        ),
        migrations.AddConstraint(
            model_name='discountcode',
            constraint=models.CheckConstraint(condition=models.Q(('percent__gte', 1), ('percent__lte', 100)), name='discount_percent_1_to_100'),
        ),
    ]
